#!/bin/bash -e
if [ "$1" == "" ]; then
  echo 1>&2 Provide hostname to restore to as first arg
  exit 1
fi
HOSTNAME=$1

ssh "postgres@$HOSTNAME" -C "service postgresql stop"
ssh "postgres@$HOSTNAME" -C "mv /var/lib/postgresql/9.1/main ~/main-old"
ssh "postgres@$HOSTNAME" -C "/usr/bin/envdir /etc/wal-e.d/env /usr/local/bin/wal-e backup-fetch /var/lib/postgresql/9.1/main LATEST"
ssh "postgres@$HOSTNAME" -C "echo \"restore_command = 'envdir /etc/wal-e.d/env /usr/local/bin/wal-e wal-fetch \\\"%f\\\" \\\"%p\\\"'\" > /var/lib/postgresql/9.1/main/recovery.conf"
ssh "postgres@$HOSTNAME" -C "chmod -R 0700 /var/lib/postgresql/9.1"
ssh "postgres@$HOSTNAME" -C "service postgresql start"
# postgres will take an unknown amount of time to restart...
exit 0

# see if databases were restored
#ssh "postgres@$HOSTNAME" -C "echo "\\\\x\\\\list" | psql"

# example query to see if IDs are complete
#ssh "postgres@$HOSTNAME" -C "echo 'select max(id) from root_saves;' | psql -d online_ruby_tutor"
